from collections.abc import Iterable
from typing import Any

class QueryResult(Iterable[dict[str, Any]]):
    def to_dict_list(self) -> list[dict[str, Any]]: ...

class GrafeoDB:
    def __init__(self, path: str = "") -> None: ...
    def execute(
        self, cypher: str, parameters: dict[str, Any] | None = None
    ) -> QueryResult: ...
    def create_node(self, labels: list[str], properties: dict[str, Any]) -> Any: ...
    def batch_create_nodes_with_props(
        self, label: str, items: list[dict[str, Any]]
    ) -> None: ...
    def create_vector_index(
        self,
        table: str,
        property_name: str,
        dimensions: int = ...,
        metric: str = ...,
    ) -> None: ...
    def create_text_index(self, table: str, property_name: str) -> None: ...
    def drop_vector_index(self, table: str, property_name: str) -> None: ...
    def drop_text_index(self, table: str, property_name: str) -> None: ...
    def vector_search(
        self,
        table: str,
        property_name: str,
        vector: list[float],
        k: int = 5,
    ) -> list[tuple[int, float]]: ...
    def text_search(
        self,
        table: str,
        property_name: str,
        query: str,
        k: int = 5,
    ) -> list[tuple[int, float]]: ...
    def get_node(self, node_id: int) -> Any: ...
    def schema(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
