"""Implementation of `kb init` — scaffold a self-contained KB directory.

`init` is intentionally idempotent: running it twice on the same directory is a
no-op (each already-present entry is reported as "exists"). It never overwrites
an existing `kb.toml`, so a user's edits are preserved.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .config import CONFIG_FILENAME, KBConfig


MANIFEST_INITIAL: dict = {
    "version": 1,
    "documents": [],
}


@dataclass(frozen=True)
class InitResult:
    """Summary of what `init` did on a target directory.

    Each entry name maps to either "created" (newly made) or "exists" (already
    present). Suitable for both human-readable output and JSON output.
    """

    kb_root: Path
    entries: dict[str, str]

    @property
    def created(self) -> list[str]:
        return sorted(name for name, status in self.entries.items() if status == "created")

    @property
    def existed(self) -> list[str]:
        return sorted(name for name, status in self.entries.items() if status == "exists")


def _ensure_dir(path: Path, entries: dict[str, str], key: str) -> None:
    if path.exists():
        if not path.is_dir():
            raise NotADirectoryError(f"Expected directory but found file at {path}")
        entries[key] = "exists"
    else:
        path.mkdir(parents=True, exist_ok=False)
        entries[key] = "created"


def _ensure_file(path: Path, content: str, entries: dict[str, str], key: str) -> None:
    if path.exists():
        if not path.is_file():
            raise IsADirectoryError(f"Expected file but found directory at {path}")
        entries[key] = "exists"
    else:
        path.write_text(content, encoding="utf-8")
        entries[key] = "created"


def init_kb(kb_root: Path, name: str | None = None) -> InitResult:
    """Scaffold a knowledge base directory at `kb_root`.

    Creates (idempotently) the following layout, based on `KBConfig` defaults:
      <kb_root>/
        kb.toml
        documents/
          raw/
          synthesized/
          manifest.json
        schema/
          migrations/
        code/
        .gitignore

    The Kuzu database directory (`graph.kuzu/`) is *not* created here; it is
    materialized by the graph layer in Step 2 when the schema is first applied.
    """
    kb_root = kb_root.expanduser().resolve()

    entries: dict[str, str] = {}
    _ensure_dir(kb_root, entries, ".")

    # Config is written first so subsequent operations could load it if needed.
    # Never overwrite an existing kb.toml — user edits are respected.
    config = KBConfig.default(name=name or kb_root.name)
    _ensure_file(kb_root / CONFIG_FILENAME, config.to_toml(), entries, CONFIG_FILENAME)

    _ensure_dir(kb_root / config.paths.documents, entries, config.paths.documents)
    _ensure_dir(kb_root / config.paths.raw, entries, config.paths.raw)
    _ensure_dir(kb_root / config.paths.synthesized, entries, config.paths.synthesized)
    _ensure_file(
        kb_root / config.paths.manifest,
        json.dumps(MANIFEST_INITIAL, indent=2) + "\n",
        entries,
        config.paths.manifest,
    )

    _ensure_dir(kb_root / config.paths.schema_dir, entries, config.paths.schema_dir)
    _ensure_dir(
        kb_root / config.paths.schema_dir / "migrations",
        entries,
        f"{config.paths.schema_dir}/migrations",
    )

    # Machine-checkable code snippets (SymPy expressions, Python reference
    # implementations) referenced by `code_path` on statically checkable nodes.
    _ensure_dir(kb_root / config.paths.code, entries, config.paths.code)

    # Sensible .gitignore so the graph DB and vector index files don't get
    # accidentally committed. Documents themselves are meant to be tracked.
    gitignore = (
        "# graphrag_knowledge_base — generated by `kb init`\n"
        "graph.kuzu/\n"
        ".index/\n"
        "__pycache__/\n"
    )
    _ensure_file(kb_root / ".gitignore", gitignore, entries, ".gitignore")

    return InitResult(kb_root=kb_root, entries=entries)
